name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "DB"
database_name = "newsnow-db"
database_id = "45f00244-e2bc-4805-aa13-4ad0aa339472"
